### ISSUE TITLE
Unit test not working

### ISSUE THREAD

**Issue by martin-danelljan** [GustavHager/pig-latinizer#11]
The unit test is not working on Ubuntu. Gives the following compilation error:

/usr/share/cmake-3.2/Modules/FindPackageHandleStandardArgs.cmake:138: error: Could NOT find GTest (missing: GTEST_LIBRARY GTEST_MAIN_LIBRARY) /usr/share/cmake-3.2/Modules/FindPackageHandleStandardArgs.cmake:374 (_FPHSA_FAILURE_MESSAGE) /usr/share/cmake-3.2/Modules/FindGTest.cmake:204 (FIND_PACKAGE_HANDLE_STANDARD_ARGS) CMakeLists.txt:6 (FIND_PACKAGE)
:-1: error: [cmake_check_build_system] Error 1

**Comment by GustavHager** [comment]
Please try the fix_test branch
